server:
  port: 5000
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true

url:
  api-currency: ${API_CURRENCY_URL:http://localhost:8080/fixer/latest}